//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF.DB.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSEREVIEW
    {
        public int ID { get; set; }
        public int COURSEID { get; set; }
        public int RATING { get; set; }
        public string COMMNET { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
