//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEF.DB.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.COURSEREVIEWs = new HashSet<COURSEREVIEW>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TEACHER { get; set; }
    
        public virtual ICollection<COURSEREVIEW> COURSEREVIEWs { get; set; }
    }
}
